### ISSUE TITLE
FIX error Cannot set headers

### ISSUE THREAD

**Issue by KeotiseuF** [We-Are-Swissborg/WASB-Back#45]

**Comment by Valdior** [comment]
C'est quoi ton erreur ? Ca ne me dit rien :/

**Comment by KeotiseuF** [comment]
> C'est quoi ton erreur ? Ca ne me dit rien :/

Lors de la récupération d'un utilisateur, à un moment, on avait une condition et le souci c'est que même si la condition était remplie, le script continuait sa route hors de la condition car on n'avait pas mis de return, ce qui donnait l'impression d'envoyer deux réponses en même temps mais avec une en-tête différente. C'est ce qui causait l'erreur au niveau du back.
